# Generated by Django 3.1 on 2020-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
