# Generated by Django 3.1 on 2020-08-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_roast_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast', to='game.player'),
        ),
    ]
