# Generated by Django 3.1 on 2020-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_length',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
