# Generated by Django 3.1 on 2020-09-27 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_round_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='kickable',
            field=models.BooleanField(default=False),
        ),
    ]
