# Generated by Django 3.1 on 2020-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200927_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
