# Generated by Django 3.1 on 2020-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201001_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='roast',
            name='roast',
            field=models.CharField(max_length=400),
        ),
    ]
